//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Property.Common.Service1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RegineUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegineUser_OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserInfo_OperationCompleted;
        
        private System.Threading.SendOrPostCallback EditUserInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditUserPwdOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMessagesOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendFaxOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback NewSendMMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMMS_TestOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMMsTestOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMessageInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendVoiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFaxRecordOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetVoiceRecordOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMessageRecordOperationCompleted;
        
        private System.Threading.SendOrPostCallback GET_SMS_MOOperationCompleted;
        
        private System.Threading.SendOrPostCallback GET_MSP_MOOperationCompleted;
        
        private System.Threading.SendOrPostCallback TelCallOperationCompleted;
        
        private System.Threading.SendOrPostCallback SMS_ReportsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::Property.Common.Properties.Settings.Default.Property_Common_Service1_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RegineUserCompletedEventHandler RegineUserCompleted;
        
        /// <remarks/>
        public event RegineUser_CompletedEventHandler RegineUser_Completed;
        
        /// <remarks/>
        public event GetUserInfoCompletedEventHandler GetUserInfoCompleted;
        
        /// <remarks/>
        public event GetUserInfo_CompletedEventHandler GetUserInfo_Completed;
        
        /// <remarks/>
        public event EditUserInfoCompletedEventHandler EditUserInfoCompleted;
        
        /// <remarks/>
        public event EditUserPwdCompletedEventHandler EditUserPwdCompleted;
        
        /// <remarks/>
        public event SendMessagesCompletedEventHandler SendMessagesCompleted;
        
        /// <remarks/>
        public event SendFaxCompletedEventHandler SendFaxCompleted;
        
        /// <remarks/>
        public event SendMMSCompletedEventHandler SendMMSCompleted;
        
        /// <remarks/>
        public event NewSendMMSCompletedEventHandler NewSendMMSCompleted;
        
        /// <remarks/>
        public event SendMMS_TestCompletedEventHandler SendMMS_TestCompleted;
        
        /// <remarks/>
        public event SendMMsTestCompletedEventHandler SendMMsTestCompleted;
        
        /// <remarks/>
        public event GetMessageInfoCompletedEventHandler GetMessageInfoCompleted;
        
        /// <remarks/>
        public event SendVoiceCompletedEventHandler SendVoiceCompleted;
        
        /// <remarks/>
        public event GetFaxRecordCompletedEventHandler GetFaxRecordCompleted;
        
        /// <remarks/>
        public event GetVoiceRecordCompletedEventHandler GetVoiceRecordCompleted;
        
        /// <remarks/>
        public event GetMessageRecordCompletedEventHandler GetMessageRecordCompleted;
        
        /// <remarks/>
        public event GET_SMS_MOCompletedEventHandler GET_SMS_MOCompleted;
        
        /// <remarks/>
        public event GET_MSP_MOCompletedEventHandler GET_MSP_MOCompleted;
        
        /// <remarks/>
        public event TelCallCompletedEventHandler TelCallCompleted;
        
        /// <remarks/>
        public event SMS_ReportsCompletedEventHandler SMS_ReportsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegineUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RegineUser(string uid, string pwd, string agent_code, string co_name, string link_man, string mob) {
            object[] results = this.Invoke("RegineUser", new object[] {
                        uid,
                        pwd,
                        agent_code,
                        co_name,
                        link_man,
                        mob});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RegineUserAsync(string uid, string pwd, string agent_code, string co_name, string link_man, string mob) {
            this.RegineUserAsync(uid, pwd, agent_code, co_name, link_man, mob, null);
        }
        
        /// <remarks/>
        public void RegineUserAsync(string uid, string pwd, string agent_code, string co_name, string link_man, string mob, object userState) {
            if ((this.RegineUserOperationCompleted == null)) {
                this.RegineUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegineUserOperationCompleted);
            }
            this.InvokeAsync("RegineUser", new object[] {
                        uid,
                        pwd,
                        agent_code,
                        co_name,
                        link_man,
                        mob}, this.RegineUserOperationCompleted, userState);
        }
        
        private void OnRegineUserOperationCompleted(object arg) {
            if ((this.RegineUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegineUserCompleted(this, new RegineUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegineUser_", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RegineUser_(string uid, string pwd, string agent_code, string co_name, string link_man, string mob, string Sign) {
            object[] results = this.Invoke("RegineUser_", new object[] {
                        uid,
                        pwd,
                        agent_code,
                        co_name,
                        link_man,
                        mob,
                        Sign});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RegineUser_Async(string uid, string pwd, string agent_code, string co_name, string link_man, string mob, string Sign) {
            this.RegineUser_Async(uid, pwd, agent_code, co_name, link_man, mob, Sign, null);
        }
        
        /// <remarks/>
        public void RegineUser_Async(string uid, string pwd, string agent_code, string co_name, string link_man, string mob, string Sign, object userState) {
            if ((this.RegineUser_OperationCompleted == null)) {
                this.RegineUser_OperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegineUser_OperationCompleted);
            }
            this.InvokeAsync("RegineUser_", new object[] {
                        uid,
                        pwd,
                        agent_code,
                        co_name,
                        link_man,
                        mob,
                        Sign}, this.RegineUser_OperationCompleted, userState);
        }
        
        private void OnRegineUser_OperationCompleted(object arg) {
            if ((this.RegineUser_Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegineUser_Completed(this, new RegineUser_CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUserInfo(string uid, string pwd) {
            object[] results = this.Invoke("GetUserInfo", new object[] {
                        uid,
                        pwd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserInfoAsync(string uid, string pwd) {
            this.GetUserInfoAsync(uid, pwd, null);
        }
        
        /// <remarks/>
        public void GetUserInfoAsync(string uid, string pwd, object userState) {
            if ((this.GetUserInfoOperationCompleted == null)) {
                this.GetUserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserInfoOperationCompleted);
            }
            this.InvokeAsync("GetUserInfo", new object[] {
                        uid,
                        pwd}, this.GetUserInfoOperationCompleted, userState);
        }
        
        private void OnGetUserInfoOperationCompleted(object arg) {
            if ((this.GetUserInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserInfoCompleted(this, new GetUserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserInfo_", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUserInfo_(string uid, string pwd) {
            object[] results = this.Invoke("GetUserInfo_", new object[] {
                        uid,
                        pwd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserInfo_Async(string uid, string pwd) {
            this.GetUserInfo_Async(uid, pwd, null);
        }
        
        /// <remarks/>
        public void GetUserInfo_Async(string uid, string pwd, object userState) {
            if ((this.GetUserInfo_OperationCompleted == null)) {
                this.GetUserInfo_OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserInfo_OperationCompleted);
            }
            this.InvokeAsync("GetUserInfo_", new object[] {
                        uid,
                        pwd}, this.GetUserInfo_OperationCompleted, userState);
        }
        
        private void OnGetUserInfo_OperationCompleted(object arg) {
            if ((this.GetUserInfo_Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserInfo_Completed(this, new GetUserInfo_CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EditUserInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EditUserInfo(string uid, string pwd, string EntName, string linkMan, string linkMobile, string Sign) {
            object[] results = this.Invoke("EditUserInfo", new object[] {
                        uid,
                        pwd,
                        EntName,
                        linkMan,
                        linkMobile,
                        Sign});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EditUserInfoAsync(string uid, string pwd, string EntName, string linkMan, string linkMobile, string Sign) {
            this.EditUserInfoAsync(uid, pwd, EntName, linkMan, linkMobile, Sign, null);
        }
        
        /// <remarks/>
        public void EditUserInfoAsync(string uid, string pwd, string EntName, string linkMan, string linkMobile, string Sign, object userState) {
            if ((this.EditUserInfoOperationCompleted == null)) {
                this.EditUserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditUserInfoOperationCompleted);
            }
            this.InvokeAsync("EditUserInfo", new object[] {
                        uid,
                        pwd,
                        EntName,
                        linkMan,
                        linkMobile,
                        Sign}, this.EditUserInfoOperationCompleted, userState);
        }
        
        private void OnEditUserInfoOperationCompleted(object arg) {
            if ((this.EditUserInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditUserInfoCompleted(this, new EditUserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EditUserPwd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EditUserPwd(string uid, string pwd, string newpwd) {
            object[] results = this.Invoke("EditUserPwd", new object[] {
                        uid,
                        pwd,
                        newpwd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EditUserPwdAsync(string uid, string pwd, string newpwd) {
            this.EditUserPwdAsync(uid, pwd, newpwd, null);
        }
        
        /// <remarks/>
        public void EditUserPwdAsync(string uid, string pwd, string newpwd, object userState) {
            if ((this.EditUserPwdOperationCompleted == null)) {
                this.EditUserPwdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditUserPwdOperationCompleted);
            }
            this.InvokeAsync("EditUserPwd", new object[] {
                        uid,
                        pwd,
                        newpwd}, this.EditUserPwdOperationCompleted, userState);
        }
        
        private void OnEditUserPwdOperationCompleted(object arg) {
            if ((this.EditUserPwdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditUserPwdCompleted(this, new EditUserPwdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMessages", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendMessages(string uid, string pwd, string tos, string msg, string otime) {
            object[] results = this.Invoke("SendMessages", new object[] {
                        uid,
                        pwd,
                        tos,
                        msg,
                        otime});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendMessagesAsync(string uid, string pwd, string tos, string msg, string otime) {
            this.SendMessagesAsync(uid, pwd, tos, msg, otime, null);
        }
        
        /// <remarks/>
        public void SendMessagesAsync(string uid, string pwd, string tos, string msg, string otime, object userState) {
            if ((this.SendMessagesOperationCompleted == null)) {
                this.SendMessagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMessagesOperationCompleted);
            }
            this.InvokeAsync("SendMessages", new object[] {
                        uid,
                        pwd,
                        tos,
                        msg,
                        otime}, this.SendMessagesOperationCompleted, userState);
        }
        
        private void OnSendMessagesOperationCompleted(object arg) {
            if ((this.SendMessagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMessagesCompleted(this, new SendMessagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendFax", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendFax(string uid, string pwd, string faxno, string men, string title, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] Bytes, string FileName) {
            object[] results = this.Invoke("SendFax", new object[] {
                        uid,
                        pwd,
                        faxno,
                        men,
                        title,
                        Bytes,
                        FileName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendFaxAsync(string uid, string pwd, string faxno, string men, string title, byte[] Bytes, string FileName) {
            this.SendFaxAsync(uid, pwd, faxno, men, title, Bytes, FileName, null);
        }
        
        /// <remarks/>
        public void SendFaxAsync(string uid, string pwd, string faxno, string men, string title, byte[] Bytes, string FileName, object userState) {
            if ((this.SendFaxOperationCompleted == null)) {
                this.SendFaxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendFaxOperationCompleted);
            }
            this.InvokeAsync("SendFax", new object[] {
                        uid,
                        pwd,
                        faxno,
                        men,
                        title,
                        Bytes,
                        FileName}, this.SendFaxOperationCompleted, userState);
        }
        
        private void OnSendFaxOperationCompleted(object arg) {
            if ((this.SendFaxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendFaxCompleted(this, new SendFaxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMMS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendMMS(string uid, string pwd, string mobno, string title, string content, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] Bytes, string mmsFileName) {
            object[] results = this.Invoke("SendMMS", new object[] {
                        uid,
                        pwd,
                        mobno,
                        title,
                        content,
                        Bytes,
                        mmsFileName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendMMSAsync(string uid, string pwd, string mobno, string title, string content, byte[] Bytes, string mmsFileName) {
            this.SendMMSAsync(uid, pwd, mobno, title, content, Bytes, mmsFileName, null);
        }
        
        /// <remarks/>
        public void SendMMSAsync(string uid, string pwd, string mobno, string title, string content, byte[] Bytes, string mmsFileName, object userState) {
            if ((this.SendMMSOperationCompleted == null)) {
                this.SendMMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMMSOperationCompleted);
            }
            this.InvokeAsync("SendMMS", new object[] {
                        uid,
                        pwd,
                        mobno,
                        title,
                        content,
                        Bytes,
                        mmsFileName}, this.SendMMSOperationCompleted, userState);
        }
        
        private void OnSendMMSOperationCompleted(object arg) {
            if ((this.SendMMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMMSCompleted(this, new SendMMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NewSendMMS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NewSendMMS(string uid, string pwd, string tos, string title, MMSContent[] mmsContentList, string otime) {
            object[] results = this.Invoke("NewSendMMS", new object[] {
                        uid,
                        pwd,
                        tos,
                        title,
                        mmsContentList,
                        otime});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NewSendMMSAsync(string uid, string pwd, string tos, string title, MMSContent[] mmsContentList, string otime) {
            this.NewSendMMSAsync(uid, pwd, tos, title, mmsContentList, otime, null);
        }
        
        /// <remarks/>
        public void NewSendMMSAsync(string uid, string pwd, string tos, string title, MMSContent[] mmsContentList, string otime, object userState) {
            if ((this.NewSendMMSOperationCompleted == null)) {
                this.NewSendMMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNewSendMMSOperationCompleted);
            }
            this.InvokeAsync("NewSendMMS", new object[] {
                        uid,
                        pwd,
                        tos,
                        title,
                        mmsContentList,
                        otime}, this.NewSendMMSOperationCompleted, userState);
        }
        
        private void OnNewSendMMSOperationCompleted(object arg) {
            if ((this.NewSendMMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NewSendMMSCompleted(this, new NewSendMMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMMS_Test", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendMMS_Test(string uid, string pwd, string mobno) {
            object[] results = this.Invoke("SendMMS_Test", new object[] {
                        uid,
                        pwd,
                        mobno});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendMMS_TestAsync(string uid, string pwd, string mobno) {
            this.SendMMS_TestAsync(uid, pwd, mobno, null);
        }
        
        /// <remarks/>
        public void SendMMS_TestAsync(string uid, string pwd, string mobno, object userState) {
            if ((this.SendMMS_TestOperationCompleted == null)) {
                this.SendMMS_TestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMMS_TestOperationCompleted);
            }
            this.InvokeAsync("SendMMS_Test", new object[] {
                        uid,
                        pwd,
                        mobno}, this.SendMMS_TestOperationCompleted, userState);
        }
        
        private void OnSendMMS_TestOperationCompleted(object arg) {
            if ((this.SendMMS_TestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMMS_TestCompleted(this, new SendMMS_TestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMMsTest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendMMsTest() {
            object[] results = this.Invoke("SendMMsTest", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendMMsTestAsync() {
            this.SendMMsTestAsync(null);
        }
        
        /// <remarks/>
        public void SendMMsTestAsync(object userState) {
            if ((this.SendMMsTestOperationCompleted == null)) {
                this.SendMMsTestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMMsTestOperationCompleted);
            }
            this.InvokeAsync("SendMMsTest", new object[0], this.SendMMsTestOperationCompleted, userState);
        }
        
        private void OnSendMMsTestOperationCompleted(object arg) {
            if ((this.SendMMsTestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMMsTestCompleted(this, new SendMMsTestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMessageInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetMessageInfo(string snum) {
            object[] results = this.Invoke("GetMessageInfo", new object[] {
                        snum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMessageInfoAsync(string snum) {
            this.GetMessageInfoAsync(snum, null);
        }
        
        /// <remarks/>
        public void GetMessageInfoAsync(string snum, object userState) {
            if ((this.GetMessageInfoOperationCompleted == null)) {
                this.GetMessageInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMessageInfoOperationCompleted);
            }
            this.InvokeAsync("GetMessageInfo", new object[] {
                        snum}, this.GetMessageInfoOperationCompleted, userState);
        }
        
        private void OnGetMessageInfoOperationCompleted(object arg) {
            if ((this.GetMessageInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMessageInfoCompleted(this, new GetMessageInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendVoice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendVoice(string uid, string pwd, string vto, string vtxt, string mode, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] FileBytes, string svrno, string str_time, string end_time) {
            object[] results = this.Invoke("SendVoice", new object[] {
                        uid,
                        pwd,
                        vto,
                        vtxt,
                        mode,
                        FileBytes,
                        svrno,
                        str_time,
                        end_time});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendVoiceAsync(string uid, string pwd, string vto, string vtxt, string mode, byte[] FileBytes, string svrno, string str_time, string end_time) {
            this.SendVoiceAsync(uid, pwd, vto, vtxt, mode, FileBytes, svrno, str_time, end_time, null);
        }
        
        /// <remarks/>
        public void SendVoiceAsync(string uid, string pwd, string vto, string vtxt, string mode, byte[] FileBytes, string svrno, string str_time, string end_time, object userState) {
            if ((this.SendVoiceOperationCompleted == null)) {
                this.SendVoiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendVoiceOperationCompleted);
            }
            this.InvokeAsync("SendVoice", new object[] {
                        uid,
                        pwd,
                        vto,
                        vtxt,
                        mode,
                        FileBytes,
                        svrno,
                        str_time,
                        end_time}, this.SendVoiceOperationCompleted, userState);
        }
        
        private void OnSendVoiceOperationCompleted(object arg) {
            if ((this.SendVoiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendVoiceCompleted(this, new SendVoiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFaxRecord", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetFaxRecord(string uid, string pwd, string num, string StartDate, string EndDate) {
            object[] results = this.Invoke("GetFaxRecord", new object[] {
                        uid,
                        pwd,
                        num,
                        StartDate,
                        EndDate});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetFaxRecordAsync(string uid, string pwd, string num, string StartDate, string EndDate) {
            this.GetFaxRecordAsync(uid, pwd, num, StartDate, EndDate, null);
        }
        
        /// <remarks/>
        public void GetFaxRecordAsync(string uid, string pwd, string num, string StartDate, string EndDate, object userState) {
            if ((this.GetFaxRecordOperationCompleted == null)) {
                this.GetFaxRecordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFaxRecordOperationCompleted);
            }
            this.InvokeAsync("GetFaxRecord", new object[] {
                        uid,
                        pwd,
                        num,
                        StartDate,
                        EndDate}, this.GetFaxRecordOperationCompleted, userState);
        }
        
        private void OnGetFaxRecordOperationCompleted(object arg) {
            if ((this.GetFaxRecordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFaxRecordCompleted(this, new GetFaxRecordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetVoiceRecord", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetVoiceRecord(string uid, string pwd, string num, string StartDate, string EndDate) {
            object[] results = this.Invoke("GetVoiceRecord", new object[] {
                        uid,
                        pwd,
                        num,
                        StartDate,
                        EndDate});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetVoiceRecordAsync(string uid, string pwd, string num, string StartDate, string EndDate) {
            this.GetVoiceRecordAsync(uid, pwd, num, StartDate, EndDate, null);
        }
        
        /// <remarks/>
        public void GetVoiceRecordAsync(string uid, string pwd, string num, string StartDate, string EndDate, object userState) {
            if ((this.GetVoiceRecordOperationCompleted == null)) {
                this.GetVoiceRecordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVoiceRecordOperationCompleted);
            }
            this.InvokeAsync("GetVoiceRecord", new object[] {
                        uid,
                        pwd,
                        num,
                        StartDate,
                        EndDate}, this.GetVoiceRecordOperationCompleted, userState);
        }
        
        private void OnGetVoiceRecordOperationCompleted(object arg) {
            if ((this.GetVoiceRecordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVoiceRecordCompleted(this, new GetVoiceRecordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMessageRecord", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetMessageRecord(string uid, string pwd, string num, string StartDate, string EndDate, string isday) {
            object[] results = this.Invoke("GetMessageRecord", new object[] {
                        uid,
                        pwd,
                        num,
                        StartDate,
                        EndDate,
                        isday});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMessageRecordAsync(string uid, string pwd, string num, string StartDate, string EndDate, string isday) {
            this.GetMessageRecordAsync(uid, pwd, num, StartDate, EndDate, isday, null);
        }
        
        /// <remarks/>
        public void GetMessageRecordAsync(string uid, string pwd, string num, string StartDate, string EndDate, string isday, object userState) {
            if ((this.GetMessageRecordOperationCompleted == null)) {
                this.GetMessageRecordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMessageRecordOperationCompleted);
            }
            this.InvokeAsync("GetMessageRecord", new object[] {
                        uid,
                        pwd,
                        num,
                        StartDate,
                        EndDate,
                        isday}, this.GetMessageRecordOperationCompleted, userState);
        }
        
        private void OnGetMessageRecordOperationCompleted(object arg) {
            if ((this.GetMessageRecordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMessageRecordCompleted(this, new GetMessageRecordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GET_SMS_MO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GET_SMS_MO(string uid, string pwd, string IDtype) {
            object[] results = this.Invoke("GET_SMS_MO", new object[] {
                        uid,
                        pwd,
                        IDtype});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GET_SMS_MOAsync(string uid, string pwd, string IDtype) {
            this.GET_SMS_MOAsync(uid, pwd, IDtype, null);
        }
        
        /// <remarks/>
        public void GET_SMS_MOAsync(string uid, string pwd, string IDtype, object userState) {
            if ((this.GET_SMS_MOOperationCompleted == null)) {
                this.GET_SMS_MOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGET_SMS_MOOperationCompleted);
            }
            this.InvokeAsync("GET_SMS_MO", new object[] {
                        uid,
                        pwd,
                        IDtype}, this.GET_SMS_MOOperationCompleted, userState);
        }
        
        private void OnGET_SMS_MOOperationCompleted(object arg) {
            if ((this.GET_SMS_MOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GET_SMS_MOCompleted(this, new GET_SMS_MOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GET_MSP_MO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GET_MSP_MO(string uid, string pwd, string IDtype) {
            object[] results = this.Invoke("GET_MSP_MO", new object[] {
                        uid,
                        pwd,
                        IDtype});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GET_MSP_MOAsync(string uid, string pwd, string IDtype) {
            this.GET_MSP_MOAsync(uid, pwd, IDtype, null);
        }
        
        /// <remarks/>
        public void GET_MSP_MOAsync(string uid, string pwd, string IDtype, object userState) {
            if ((this.GET_MSP_MOOperationCompleted == null)) {
                this.GET_MSP_MOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGET_MSP_MOOperationCompleted);
            }
            this.InvokeAsync("GET_MSP_MO", new object[] {
                        uid,
                        pwd,
                        IDtype}, this.GET_MSP_MOOperationCompleted, userState);
        }
        
        private void OnGET_MSP_MOOperationCompleted(object arg) {
            if ((this.GET_MSP_MOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GET_MSP_MOCompleted(this, new GET_MSP_MOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TelCall", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TelCall(string uid, string pwd, string host_call, string caller) {
            object[] results = this.Invoke("TelCall", new object[] {
                        uid,
                        pwd,
                        host_call,
                        caller});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TelCallAsync(string uid, string pwd, string host_call, string caller) {
            this.TelCallAsync(uid, pwd, host_call, caller, null);
        }
        
        /// <remarks/>
        public void TelCallAsync(string uid, string pwd, string host_call, string caller, object userState) {
            if ((this.TelCallOperationCompleted == null)) {
                this.TelCallOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTelCallOperationCompleted);
            }
            this.InvokeAsync("TelCall", new object[] {
                        uid,
                        pwd,
                        host_call,
                        caller}, this.TelCallOperationCompleted, userState);
        }
        
        private void OnTelCallOperationCompleted(object arg) {
            if ((this.TelCallCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TelCallCompleted(this, new TelCallCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SMS_Reports", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SMS_Reports(string uid, string pwd) {
            object[] results = this.Invoke("SMS_Reports", new object[] {
                        uid,
                        pwd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SMS_ReportsAsync(string uid, string pwd) {
            this.SMS_ReportsAsync(uid, pwd, null);
        }
        
        /// <remarks/>
        public void SMS_ReportsAsync(string uid, string pwd, object userState) {
            if ((this.SMS_ReportsOperationCompleted == null)) {
                this.SMS_ReportsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSMS_ReportsOperationCompleted);
            }
            this.InvokeAsync("SMS_Reports", new object[] {
                        uid,
                        pwd}, this.SMS_ReportsOperationCompleted, userState);
        }
        
        private void OnSMS_ReportsOperationCompleted(object arg) {
            if ((this.SMS_ReportsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SMS_ReportsCompleted(this, new SMS_ReportsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MMSContent {
        
        private byte[] musicByteField;
        
        private string musicTypeField;
        
        private byte[] imgByteField;
        
        private string textField;
        
        private string imgTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] MusicByte {
            get {
                return this.musicByteField;
            }
            set {
                this.musicByteField = value;
            }
        }
        
        /// <remarks/>
        public string MusicType {
            get {
                return this.musicTypeField;
            }
            set {
                this.musicTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ImgByte {
            get {
                return this.imgByteField;
            }
            set {
                this.imgByteField = value;
            }
        }
        
        /// <remarks/>
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public string ImgType {
            get {
                return this.imgTypeField;
            }
            set {
                this.imgTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void RegineUserCompletedEventHandler(object sender, RegineUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegineUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegineUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void RegineUser_CompletedEventHandler(object sender, RegineUser_CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegineUser_CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegineUser_CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetUserInfoCompletedEventHandler(object sender, GetUserInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetUserInfo_CompletedEventHandler(object sender, GetUserInfo_CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserInfo_CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserInfo_CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EditUserInfoCompletedEventHandler(object sender, EditUserInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EditUserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EditUserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EditUserPwdCompletedEventHandler(object sender, EditUserPwdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EditUserPwdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EditUserPwdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void SendMessagesCompletedEventHandler(object sender, SendMessagesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMessagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMessagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void SendFaxCompletedEventHandler(object sender, SendFaxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendFaxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendFaxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void SendMMSCompletedEventHandler(object sender, SendMMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void NewSendMMSCompletedEventHandler(object sender, NewSendMMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NewSendMMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NewSendMMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void SendMMS_TestCompletedEventHandler(object sender, SendMMS_TestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMMS_TestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMMS_TestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void SendMMsTestCompletedEventHandler(object sender, SendMMsTestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMMsTestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMMsTestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetMessageInfoCompletedEventHandler(object sender, GetMessageInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMessageInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMessageInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void SendVoiceCompletedEventHandler(object sender, SendVoiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendVoiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendVoiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetFaxRecordCompletedEventHandler(object sender, GetFaxRecordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFaxRecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFaxRecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetVoiceRecordCompletedEventHandler(object sender, GetVoiceRecordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVoiceRecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVoiceRecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetMessageRecordCompletedEventHandler(object sender, GetMessageRecordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMessageRecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMessageRecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GET_SMS_MOCompletedEventHandler(object sender, GET_SMS_MOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GET_SMS_MOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GET_SMS_MOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GET_MSP_MOCompletedEventHandler(object sender, GET_MSP_MOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GET_MSP_MOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GET_MSP_MOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void TelCallCompletedEventHandler(object sender, TelCallCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TelCallCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TelCallCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void SMS_ReportsCompletedEventHandler(object sender, SMS_ReportsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SMS_ReportsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SMS_ReportsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591